#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           BRD,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BLD,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LI,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           launch1,       tmotorVex393HighSpeed_MC29, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port5,           launch2,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port6,           launch3,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           launch4,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port8,           RI,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           FLD,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          FRD,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Gearbox on the launcher.
const float LAUNCH_RATIO = (86 * 86) / (36 * 12);

//Wheel speed in RPM.
const int SPEED[] = {1000, 2000};

//Tank drive
void drive(int left, int right)
{
	motor[BLD] = motor[FLD] = left;
	motor[BRD] = motor[FRD] = right;
}

void intake(int speed)
{
	motor[LI] = motor[RI] = speed;
}

task launchControl()
{
	int targetSpeed = 0,
		motorSpeed = 0,
		select = 0;

	//All motors are controlled by the encoder.
	slaveMotor(launch2, launch1);
	slaveMotor(launch3, launch1);
	slaveMotor(launch4, launch1);

	while (true)
	{
		//Select speed setting.
		if (vexRT[Btn8D])
			select = 0;
		else if (vexRT[Btn8R])
			select = 1;

		//Set target speed for the motors.
		targetSpeed = (int)(SPEED[select] / LAUNCH_RATIO) * vexRT[Btn6U];

		//Motor speed aproaches target.
		motorSpeed += sgn(targetSpeed - getMotorVelocity(launch1));
		motor[launch1] = motorSpeed;
	}
}



void pre_auton()
{
  bStopTasksBetweenModes = true;
}



task autonomous()
{
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}



task usercontrol()
{
	startTask(launchControl);

	while (true)
	{
		drive(vexRT[Ch3], vexRT[Ch2]);
		intake(127 * (vexRT[Btn5U] - vexRT[Btn5D]));
	}
}
