#pragma config(Motor,  port1,           BRD,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BLD,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           intakeL,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           launch1,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           launch2,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           launch3,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           launch4,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           intakeR,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           FLD,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          FRD,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void tankDrive(int left, int right)
{
	motor[BLD] = motor[FLD] = left;
	motor[BRD] = motor[FRD] = right;
}

void intake(int speed)
{
	motor[intakeL] = motor[intakeR] = speed;
}

task PIDLaunchControl()
{

}

void pre_auton()
{
  bStopTasksBetweenModes = true;
}



task autonomous()
{
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}



task usercontrol()
{
	//startTask(PIDLaunchControl);

	while (true)
	{
		motor[launch1] = motor[launch2] = motor[launch3] = motor[launch4] = 127 * vexRT[Btn6U];
		tankDrive(vexRT[Ch3] /*Left*/ , vexRT[Ch2] /*Right*/ );
		intake(127 * (vexRT[Btn5U] - vexRT[Btn5D]));
	}
}
